try:
    import support.auxillary
except Exception as e:
    print(e)